name: Build Hekate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential
        sudo apt-get -y install git
        sudo apt-get -y install python3
        sudo apt-get -y install python3-pip
        sudo pip3 install -U pyopenssl
        sudo pip3 install -U cryptography
        sudo pip3 install -U construct
        sudo pip3 install -U pycryptodomex

    - name: Build Hekate
      run: |
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hekate-binary
        path: .
